#!/bin/sh

export OPENAI_API_KEY=
export HUGGINGFACEHUB_API_TOKEN="$HUGGINGFACEHUB_API_SECRET"
export _BARD_API_KEY=
export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_KEY_SECRET"
export GOOGLE_API_KEY="$GOOGLE_API_SECRET"
export DOCS_PERSIST_DIRECTORY=./db_docs/
export IMAGES_PERSIST_DIRECTORY=./db_images/
#export HF_HOME=./hf_cache/
